### ISSUE TITLE
Category.xml refers to the features with a wrong ID

### ISSUE THREAD

**Issue by sdkrach** [MDSD-Tools/ThirdParty-Library#2]
Currently, installing dependencies in Eclipse is only possible when deselecting the checkbox "Group items by category". Otherwise, only the feature gets installed, but not the included plugins. The reason is probably that the Category refers to the feature using a different (wrong?) id.

Maven Dependencies/Mockito JUnit5 Extension -->org.mockito.junit.jupiter.feature.feature.jar 
Mockito JUnit5 Extension (without Categories) --> org.mockito.junit.jupiter.feature.feature.group

**Comment by seiferma** [comment]
The query in the category.xml file is wrong. As far as I understand, the content of an update site consists of bundles, features, and installable features. The id of the latter ends with `.feature.group`. The latter also do not provide any code but only require code provided by other features.

The query in the category.xml included everything that provides an installable unit. While this matches the installable fatures, it also matches the features. I adjusted the query to only include features that only provide installable units. In the simplified example below, this means that we only select units that only have `org.eclipse.equinox.p2.iu` elements in the `provides` group.

```
<unit id='org.mockito.junit.jupiter.feature.feature.group' version='2.23.0' singleton='false'>
	<update id='org.mockito.junit.jupiter.feature.feature.group' range='[0.0.0,2.23.0)' severity='0'/>
	<provides size='1'>
		<provided namespace='org.eclipse.equinox.p2.iu' name='org.mockito.junit.jupiter.feature.feature.group' version='2.23.0'/>
	</provides>
	<requires size='2'>
		<required namespace='org.eclipse.equinox.p2.iu' name='org.mockito.junit-jupiter' range='[2.23.0,2.23.0]'/>
		<required namespace='org.eclipse.equinox.p2.iu' name='org.mockito.junit.jupiter.feature.feature.jar' range='[2.23.0,2.23.0]'/>
	</requires>
</unit>
<unit id='org.mockito.junit.jupiter.feature.feature.jar' version='2.23.0'>
	<provides size='3'>
		<provided namespace='org.eclipse.equinox.p2.iu' name='org.mockito.junit.jupiter.feature.feature.jar' version='2.23.0'/>
		<provided namespace='org.eclipse.equinox.p2.eclipse.type' name='feature' version='1.0.0'/>
		<provided namespace='org.eclipse.update.feature' name='org.mockito.junit.jupiter.feature' version='2.23.0'/>
	</provides>
	<filter>
	(org.eclipse.update.install.features=true)
	</filter>
	<artifacts size='1'>
		<artifact classifier='org.eclipse.update.feature' id='org.mockito.junit.jupiter.feature' version='2.23.0'/>
	</artifacts>
</unit>
```

Some useful source for formulating these queries is the [wiki page about the p2 query language](https://wiki.eclipse.org/Equinox/p2/Query_Language_for_p2).

**Comment by sdkrach** [comment]
#3 fixes the problem. Now both views refer to the feature.group.
